name: Build HEASoft (Xspec only) Docker image

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  download_heasoft:
    name: Download HEASoft
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Get HEASoft version
        id: get_version
        run: |
          VERSION=$(cat version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "HEASOFT_FILE=heasoft-${VERSION}src.tar.gz" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Download HEASoft
        run: |
          sudo apt-get install -y aria2
          aria2c -x 16 -s 16 --show-console-readout=true \
            "https://heasarc.gsfc.nasa.gov/cgi-bin/Tools/tarit/tarit.pl?mode=download&arch=src&src_pc_linux_ubuntu=Y&src_other_specify=&general=heasptools&general=heagen&xanadu=xspec"
          if [ ! -f "$HEASOFT_FILE" ]; then
            echo "$HEASOFT_FILE does not exist. The version could be wrong."
            exit 1  # Exit with a non-zero status to fail the job
          fi

      - name: Upload HEASoft as artifact
        uses: actions/upload-artifact@v4
        with:
          name: heasoft
          path: ${{ env.HEASOFT_FILE }}
          retention-days: 1

  push_image:
    name: Build & Push Docker (${{ matrix.platform }})
    needs: download_heasoft
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        platform: [ linux/amd64, linux/arm64 ]
        include:
          - platform: linux/amd64
            runner: ubuntu-22.04
          - platform: linux/arm64
            runner: ubuntu-22.04-arm
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      # The next three steps are needed to ensure there is enough disk space,
      # see https://github.com/easimon/maximize-build-space/issues/41
      - name: Move /var/lib/docker/
        run: sudo mv /var/lib/docker/ "${GITHUB_WORKSPACE}/docker"

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          temp-reserve-mb: 32
          swap-size-mb: 32
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          build-mount-path: /var/lib/docker/

      - name: Restore /var/lib/docker/
        run: sudo sh -c "mv ${GITHUB_WORKSPACE}/docker/* /var/lib/docker"

      - name: Download HEASoft artifact
        uses: actions/download-artifact@v4
        with:
          name: heasoft
          path: /var/lib/docker/

      - name: Get HEASoft version
        run: |
          echo "VERSION=${{ needs.download_heasoft.outputs.version }}" >> $GITHUB_ENV

      - name: Extract HEASoft
        run: |
          cd /var/lib/docker/
          tar -zxvf "heasoft-${VERSION}src.tar.gz"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/heasoft
          tags: type=raw,${{ env.VERSION }}

      - name: Build and push Docker image (${{ matrix.platform }})
        id: push
        uses: docker/build-push-action@v6
        with:
          network: host
          build-args: version=${{ env.VERSION }}
          context: /var/lib/docker/
          file: /var/lib/docker/heasoft-${{ env.VERSION }}/Docker/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/${{ secrets.DOCKER_USERNAME }}/heasoft
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
