name: Build HEASoft (Xspec only) Docker image

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  REGISTRY_IMAGE: ${{ secrets.DOCKER_USERNAME }}/heasoft

jobs:
  download:
    name: Download HEASoft
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Get HEASoft version
        id: get_version
        run: |
          VERSION=$(cat version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "HEASOFT_FILE=heasoft-${VERSION}src.tar.gz" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Download HEASoft
        run: |
          sudo apt-get install -y aria2
          aria2c -x 16 -s 16 --show-console-readout=true \
            "https://heasarc.gsfc.nasa.gov/cgi-bin/Tools/tarit/tarit.pl?mode=download&arch=src&src_pc_linux_ubuntu=Y&src_other_specify=&general=heasptools&general=heagen&xanadu=xspec"
          if [ ! -f "$HEASOFT_FILE" ]; then
            echo "$HEASOFT_FILE does not exist. The version could be wrong."
            exit 1  # Exit with a non-zero status to fail the job
          fi

      - name: Upload HEASoft as artifact
        uses: actions/upload-artifact@v4
        with:
          name: heasoft
          path: ${{ env.HEASOFT_FILE }}
          retention-days: 1

  build:
    name: Build & Push Docker (${{ matrix.platform }})
    needs: download
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        platform: [ linux/amd64, linux/arm64 ]
        include:
          - platform: linux/amd64
            runner: ubuntu-22.04
          - platform: linux/arm64
            runner: ubuntu-22.04-arm
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    env:
      VERSION: ${{ needs.download.outputs.version }}
    steps:
      # The next three steps are needed to ensure there is enough disk space,
      # see https://github.com/easimon/maximize-build-space/issues/41
      - name: Move /var/lib/docker/
        run: sudo mv /var/lib/docker/ "${GITHUB_WORKSPACE}/docker"

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          temp-reserve-mb: 32
          swap-size-mb: 32
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          build-mount-path: /var/lib/docker/

      - name: Restore /var/lib/docker/
        run: sudo sh -c "mv ${GITHUB_WORKSPACE}/docker/* /var/lib/docker"

      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Download HEASoft artifact
        uses: actions/download-artifact@v4
        with:
          name: heasoft
          path: /var/lib/docker/

      - name: Extract HEASoft
        run: |
          cd /var/lib/docker/
          tar -zxvf "heasoft-${{ env.VERSION }}src.tar.gz"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push by digest (${{ matrix.platform }})
        id: build
        uses: docker/build-push-action@v6
        with:
          network: host
          build-args: version=${{ env.VERSION }}
          context: /var/lib/docker/
          file: /var/lib/docker/heasoft-${{ env.VERSION }}/Docker/Dockerfile
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ env.REGISTRY_IMAGE }}
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    needs: [download, build]
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=raw,value=${{ needs.download.outputs.version }}

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}
